# Generated by Django 3.1.7 on 2021-04-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.provincia'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.zona'),
        ),
    ]
