# Generated by Django 3.2.1 on 2021-05-07 17:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20210502_1838'),
        ('empleado', '0002_alter_cargo_descripcion'),
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtencionSecundaria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIncidente', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Incidente')),
                ('detalle', models.TextField(blank=True, null=True, verbose_name='Detalle')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha Salida')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora Salida')),
                ('instalacion', models.BooleanField(verbose_name='Instalación')),
                ('configuracion', models.BooleanField(verbose_name='Configuración')),
                ('prueba', models.BooleanField(verbose_name='Prueba')),
                ('capacitacion', models.BooleanField(verbose_name='Capacitación')),
                ('hardware', models.BooleanField(verbose_name='Hardware')),
                ('software', models.BooleanField(verbose_name='Software')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('tipoDocumento', models.CharField(choices=[('1', 'REPORTE DE ENTREGA'), ('2', 'REPORTE DE RECEPCIÓN'), ('3', 'REPORTE DE ENTREGA Y ATENCIÓN'), ('4', 'REPORTE ENTREGA A BIENES')], default='1', max_length=1, verbose_name='Tipo Documento')),
                ('contadorDocumento', models.IntegerField(default=0)),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Responsable de Tics')),
            ],
            options={
                'verbose_name': 'Atención Secundaria',
                'verbose_name_plural': 'Atenciones secundaria',
            },
        ),
        migrations.CreateModel(
            name='AtencionSecundariaDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('cabecera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.atencionsecundaria')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inventariotics')),
            ],
            options={
                'verbose_name': 'Atención Secundaria Detalle',
                'verbose_name_plural': 'Atención Secundaria Detalles',
            },
        ),
    ]
