# Generated by Django 3.2 on 2021-04-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atencion', '0001_initial'),
        ('empleado', '0006_merge_20210405_0838'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atenciondetalle',
            name='pieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inventariotics'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.invetariodistritocabecera'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='tipoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atencion.tipodocumento'),
        ),
    ]
