# Generated by Django 3.1.7 on 2021-04-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fechaIncidente',
            field=models.DateField(verbose_name='Fecha Incidente'),
        ),
    ]
