# Generated by Django 3.2 on 2021-04-23 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Responsable de Tics'),
        ),
    ]
