# Generated by Django 3.2 on 2021-04-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='fecha_salida',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Salida'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Salida'),
        ),
    ]
