# Generated by Django 3.2.1 on 2021-05-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_cargo_descripcion'),
        ('atencion', '0003_atencionsecundaria_recibe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencionsecundaria',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Entrega'),
        ),
    ]
