# Generated by Django 3.1.7 on 2021-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0005_auto_20210404_0311'),
        ('atencion', '0002_auto_20210402_2024'),
    ]

    operations = [
    ]
