# Generated by Django 3.2 on 2021-04-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0006_merge_20210405_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='atencion',
            name='contadorDocumento',
            field=models.IntegerField(default=0),
        ),
    ]
