# Generated by Django 3.2 on 2021-04-18 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0006_merge_20210405_0838'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Entrega')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Devolución')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='observación')),
                ('estado', models.BooleanField(verbose_name='Devuelto?')),
                ('condicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.condicion', verbose_name='estado de la  devolución')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inventariotics', verbose_name='Item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Préstamo Devolución',
                'verbose_name_plural': 'Prestamos Devoluciones',
            },
        ),
    ]
