# Generated by Django 3.1.7 on 2021-03-31 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_auto_20210331_1122'),
        ('empleado', '0003_merge_20210331_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha Entrega')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Devolución')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='observación')),
                ('estado', models.BooleanField(verbose_name='Devuelto?')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.condicion', verbose_name='Condición de devolución')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventariotics', verbose_name='Item')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Préstamo Devolución',
                'verbose_name_plural': 'Prestamos Devoluciones',
            },
        ),
    ]
