# Generated by Django 3.1.7 on 2021-03-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_auto_20210331_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(default=False, verbose_name='Devuelto?'),
        ),
    ]
