# Generated by Django 3.2.1 on 2021-05-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_alter_prestamo_condicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='condicion',
            field=models.CharField(blank=True, choices=[('1', 'BUENO'), ('2', 'DAÑADO')], max_length=1, null=True, verbose_name='estado de la  devolución'),
        ),
    ]
