# Generated by Django 3.1.7 on 2021-04-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_merge_20210331_0844'),
        ('inventario', '0003_merge_20210401_0902'),
        ('prestamo', '0004_auto_20210331_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='condicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.condicion', verbose_name='estado de la  devolución'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inventariotics', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
    ]
