# Generated by Django 3.2 on 2021-05-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Area')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.distrito')),
            ],
            options={
                'verbose_name': 'area',
                'verbose_name_plural': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='UnidadAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Unidad de Atención')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Unidad de Atención')),
            ],
            options={
                'verbose_name': 'Unidad de Atención',
                'verbose_name_plural': 'Unidad de Atenciones',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Ingreso')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('genero', models.CharField(choices=[('1', 'MASCULINO'), ('2', 'FEMENINO'), ('3', 'GLBTI')], default='2', max_length=1, verbose_name='Género')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
                ('cedula', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cédula')),
                ('telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Télefono móvil')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Empleados/%Y/%m/%d/', verbose_name='Foto')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.cargo')),
                ('unidadAtencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empleado.unidadatencion', verbose_name='Unidad de Atención')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
