# Generated by Django 3.2.1 on 2021-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Empleado está activo'),
        ),
    ]
