# Generated by Django 3.2.1 on 2021-05-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cargo'),
        ),
    ]
