# Generated by Django 3.1.7 on 2021-03-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='genero',
            field=models.CharField(choices=[('1', 'MASCULINO'), ('2', 'FEMENINO'), ('3', 'GLBTI')], default='2', max_length=1, verbose_name='Género'),
        ),
    ]
