# Generated by Django 3.1.7 on 2021-04-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_auto_20210401_0903'),
        ('empleado', '0003_merge_20210331_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='distrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.distrito'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='unidadAtencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empleado.unidadatencion', verbose_name='Unidad de Atención'),
        ),
        migrations.AlterField(
            model_name='unidadatencion',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Unidad de Atención'),
        ),
    ]
