# Generated by Django 3.1.7 on 2021-04-04 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_auto_20210401_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadatencion',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Unidad de Atención'),
        ),
    ]
