# Generated by Django 3.1.7 on 2021-04-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0004_auto_20210401_0953'),
        ('empleado', '0004_auto_20210401_1121'),
    ]

    operations = [
    ]
