# Generated by Django 3.1.7 on 2021-04-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_auto_20210403_2046'),
        ('empleado', '0005_merge_20210401_1134'),
    ]

    operations = [
    ]
