# Generated by Django 3.2.3 on 2021-05-20 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Capacidad Disco',
                'verbose_name_plural': 'Capacidad Discos',
            },
        ),
        migrations.CreateModel(
            name='CapacidadMemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Capacidad Memoria Ram',
                'verbose_name_plural': 'Capacidad Memoria Ram',
            },
        ),
        migrations.CreateModel(
            name='ImpresoraTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='impresora Tecnologia')),
            ],
            options={
                'verbose_name': 'Impresora Tecnologia',
                'verbose_name_plural': 'Impresora Tecnologia',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Sistema Operativo',
                'verbose_name_plural': 'Sistema Operativos',
            },
        ),
        migrations.CreateModel(
            name='SoftwareAntivirus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Software Antivirus')),
            ],
            options={
                'verbose_name': 'Software Antivirus',
                'verbose_name_plural': 'Software Antivirus',
            },
        ),
        migrations.CreateModel(
            name='SoftwareOfimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Software Ofimática')),
            ],
            options={
                'verbose_name': 'Software Ofimatica',
                'verbose_name_plural': 'Software Ofimatica',
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Tipo Dispositivo')),
            ],
            options={
                'verbose_name': 'Tipo Dispositivo',
                'verbose_name_plural': 'Tipo Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Tipo Equipo')),
            ],
            options={
                'verbose_name': 'Tipo Equipo',
                'verbose_name_plural': 'Tipo Equipos',
            },
        ),
        migrations.CreateModel(
            name='TipoImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Tipo Impresora')),
            ],
            options={
                'verbose_name': 'Tipo Impresora',
                'verbose_name_plural': 'Tipo Impresoras',
            },
        ),
        migrations.CreateModel(
            name='InventarioTics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Descripción')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serie')),
                ('codigoMies', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Mies')),
                ('condicion', models.CharField(blank=True, choices=[('1', 'NUEVO'), ('2', 'BUENO'), ('3', 'DAÑADO')], max_length=1, null=True, verbose_name='Condición')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='InventarioTics/%Y/%m/%d/', verbose_name='Foto')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo')),
            ],
            options={
                'verbose_name': 'Inventario Tics',
                'verbose_name_plural': 'Inventario Tics',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('1', 'COMPUTADORAS'), ('2', 'IMPRESORAS'), ('3', 'OTROS DISPOSITIVOS')], default='1', max_length=1, verbose_name='Categoria')),
                ('nombreEquipo', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre del equipo')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serie')),
                ('codigoMies', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Mies')),
                ('direccionIp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Ip')),
                ('direccionMac', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Mac Address')),
                ('softwareAdicional', models.CharField(blank=True, max_length=240, null=True, verbose_name='Software Adicional')),
                ('estado', models.CharField(choices=[('1', 'BUENO'), ('2', 'REGULAR'), ('3', 'MALO')], default='1', max_length=1, verbose_name='Estado')),
                ('observacion', models.CharField(blank=True, max_length=240, null=True, verbose_name='Observación')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='dispositivo/%Y/%m/%d/', verbose_name='Foto')),
                ('antivirus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.softwareantivirus')),
                ('capacidadDisco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidaddisco', verbose_name='Capacidad Disco Duro')),
                ('capacidadMemoriaRam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidadmemoriaram', verbose_name='Tamaño Memoria Ram')),
                ('capacidadProcesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.procesador', verbose_name='Procesador')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo')),
                ('ofimatica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.softwareofimatica')),
                ('sistemaOperativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.sistemaoperativo')),
                ('tecnologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.impresoratecnologia')),
                ('tipoDispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipodispositivo')),
                ('tipoEquipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoequipo')),
                ('tipoImpresora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoimpresora')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
