# Generated by Django 3.2.1 on 2021-05-14 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0002_alter_empleado_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadDisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Capacidad Disco',
                'verbose_name_plural': 'Capacidad Discos',
            },
        ),
        migrations.CreateModel(
            name='CapacidadMemoriaRam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Capacidad Memoria Ram',
                'verbose_name_plural': 'Capacidad Memoria Ram',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
        migrations.CreateModel(
            name='Procesador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Procesador',
                'verbose_name_plural': 'Procesadores',
            },
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('1', 'COMPUTADORAS'), ('2', 'IMPRESORAS'), ('3', 'OTROS DISPOSITIVOS')], default='1', max_length=1, verbose_name='Tipo Inventario')),
                ('nombreEquipo', models.CharField(blank=True, max_length=80, null=True, verbose_name='Nombre del equipo')),
                ('tipoEquipo', models.CharField(choices=[('1', 'ALL IN ONE'), ('2', 'DESKTOP'), ('3', 'LAPTOP'), ('4', 'SERVIDOR')], max_length=1, verbose_name='Tipo Inventario')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serie')),
                ('codigoMies', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Mies')),
                ('sistemaOperativo', models.CharField(blank=True, choices=[('1', 'WINDOWS XP'), ('2', 'WINDOWS VISTA'), ('3', 'WINDOWS 7'), ('4', 'WINDOWS 8'), ('5', 'WINDOWS 10'), ('6', 'LINUX'), ('7', 'IOS'), ('8', 'OTROS')], max_length=1, null=True, verbose_name='Sistema Operativo')),
                ('direccionIp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Ip')),
                ('direccionMac', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Mac Address')),
                ('ofimatica', models.CharField(blank=True, choices=[('1', 'MICROSOFT OFFICE'), ('2', 'LIBRE OFFICE'), ('3', 'OPEN OFFICE'), ('4', 'OTROS')], max_length=1, null=True, verbose_name='Software Ofimática')),
                ('antivirus', models.CharField(blank=True, choices=[('1', 'KASPERSKY'), ('2', 'AVAST'), ('3', 'AVG'), ('4', 'ESET'), ('5', 'AVIRA'), ('6', 'OTRO')], max_length=1, null=True, verbose_name='Software Antivirus')),
                ('softwareAdicional', models.CharField(blank=True, max_length=240, null=True, verbose_name='Software Adicional')),
                ('tecnologia', models.CharField(blank=True, choices=[('1', 'LASER'), ('2', 'MATRICIAL'), ('3', 'INYECCIÓN A TINTA')], max_length=1, null=True, verbose_name='Tecnologia')),
                ('tipoImpresora', models.CharField(blank=True, choices=[('1', 'MULTIFUNCIÓN B/N'), ('2', 'MULTIFUNCIÓN COLOR'), ('3', 'SIMPLE B/N'), ('4', 'SIMPLE COLOR')], max_length=1, null=True, verbose_name='Tipo Impresora')),
                ('tipoDispositivo', models.CharField(blank=True, choices=[('1', 'MONITOR'), ('2', 'PROYECTOR'), ('3', 'ESCANER'), ('4', 'TELEVISOR'), ('5', 'OTRO')], max_length=1, null=True, verbose_name='Software Ofimática')),
                ('estado', models.CharField(choices=[('1', 'BUENO'), ('2', 'REGULAR'), ('3', 'MALO')], default='1', max_length=1, verbose_name='Estado')),
                ('observacion', models.CharField(max_length=240, verbose_name='Observación')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='dispositivo/%Y/%m/%d/', verbose_name='Foto')),
                ('capacidadDisco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidaddisco', verbose_name='Capacidad Disco Duro')),
                ('capacidadMemoriaRam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidadmemoriaram', verbose_name='Tamaño Memoria Ram')),
                ('capacidadProcesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.procesador', verbose_name='Procesador')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo')),
                ('unidadAdministrativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area', verbose_name='Unidad administrativa')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
    ]
