# Generated by Django 3.2.1 on 2021-05-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='unidadAdministrativa',
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipoDispositivo',
            field=models.CharField(blank=True, choices=[('1', 'MONITOR'), ('2', 'PROYECTOR'), ('3', 'ESCANER'), ('4', 'TELEVISOR'), ('5', 'OTRO')], max_length=1, null=True, verbose_name='Tipo Dispositivo'),
        ),
    ]
