# Generated by Django 3.2 on 2021-04-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoCabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIngreso', models.DateField(verbose_name='Fecha Ingreso')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción / Nombre')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serie')),
                ('codigoMies', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Mies')),
                ('direccionIp', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Ip')),
                ('direccionMac', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Mac Address')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='Equipo/%Y/%m/%d/', verbose_name='Foto')),
                ('capacidadDisco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidaddisco')),
                ('capacidadMemoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidadmemoriaram')),
                ('capacidadProcesador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.procesador')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria')),
                ('condicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.condicion')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo')),
            ],
            options={
                'verbose_name': 'Invetario Distrito ',
                'verbose_name_plural': 'Invetario Distrito ',
            },
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='codigoMies',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Mies'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='direccionIp',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Ip'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='direccionMac',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Mac Address'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serie'),
        ),
        migrations.CreateModel(
            name='EquipoDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('cabeceraDistrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.equipocabecera')),
                ('periferico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.inventariotics')),
            ],
            options={
                'verbose_name': 'Inventario Distrito Detalle',
                'verbose_name_plural': 'Inventario Distrito Detalles',
            },
        ),
    ]
