# Generated by Django 3.2 on 2021-04-19 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodistritodetalle',
            name='cabeceraDistrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.invetariodistritocabecera'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='cantidad',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
