# Generated by Django 3.1.7 on 2021-04-01 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20210331_1122'),
        ('inventario', '0002_auto_20210331_1035'),
    ]

    operations = [
    ]
