# Generated by Django 3.2 on 2021-05-02 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custodio', '0002_alter_custodio_equipo'),
        ('inventario', '0002_auto_20210424_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='capacidadDisco',
        ),
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='capacidadMemoria',
        ),
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='capacidadProcesador',
        ),
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='condicion',
        ),
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='invetariodistritocabecera',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='equipocabecera',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.marca'),
        ),
        migrations.AlterField(
            model_name='equipocabecera',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo'),
        ),
        migrations.DeleteModel(
            name='InventarioDistritoDetalle',
        ),
        migrations.DeleteModel(
            name='InvetarioDistritoCabecera',
        ),
    ]
