# Generated by Django 3.2.1 on 2021-05-14 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20210513_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='categoria',
            field=models.CharField(choices=[('1', 'COMPUTADORAS'), ('2', 'IMPRESORAS'), ('3', 'OTROS DISPOSITIVOS')], default='1', max_length=1, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipoEquipo',
            field=models.CharField(blank=True, choices=[('1', 'ALL IN ONE'), ('2', 'DESKTOP'), ('3', 'LAPTOP'), ('4', 'SERVIDOR')], max_length=1, null=True, verbose_name='Tipo Equipo'),
        ),
    ]
