# Generated by Django 3.2 on 2021-04-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20210419_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='codigoMies',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Mies'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='direccionIp',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Ip'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='direccionMac',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Mac Address'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serie'),
        ),
    ]
