# Generated by Django 3.1.7 on 2021-04-01 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0002_auto_20210401_0903'),
        ('empleado', '0003_merge_20210331_0844'),
        ('inventario', '0003_merge_20210401_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodistritodetalle',
            name='cabeceraDistrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.invetariodistritocabecera'),
        ),
        migrations.AlterField(
            model_name='inventariodistritodetalle',
            name='periferico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.inventariotics'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.condicion'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicacion.distrito'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='capacidadDisco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidaddisco'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='capacidadMemoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidadmemoriaram'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='capacidadProcesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.procesador'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.condicion'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.marca'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='invetariodistritocabecera',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area'),
        ),
    ]
