# Generated by Django 3.2.1 on 2021-05-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_cargo_descripcion'),
        ('inventario', '0003_auto_20210502_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocabecera',
            name='capacidadDisco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidaddisco', verbose_name='Disco Duro'),
        ),
        migrations.AlterField(
            model_name='equipocabecera',
            name='capacidadMemoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.capacidadmemoriaram', verbose_name='Memoria Ram'),
        ),
        migrations.AlterField(
            model_name='equipocabecera',
            name='capacidadProcesador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.procesador', verbose_name='Procesador'),
        ),
        migrations.AlterField(
            model_name='equipocabecera',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='equipocabecera',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.condicion', verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='condicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.condicion', verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area', verbose_name='Ubicación'),
        ),
    ]
