# Generated by Django 3.2.1 on 2021-05-14 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20210513_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='observacion',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Observación'),
        ),
    ]
