# Generated by Django 3.2.1 on 2021-05-14 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_dispositivo_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpresoraTecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='impresora Tecnologia')),
            ],
            options={
                'verbose_name': 'impresoraTecnologia',
                'verbose_name_plural': 'impresoraTecnologia',
            },
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Sistema Operativo')),
            ],
            options={
                'verbose_name': 'Sistema Operativo',
                'verbose_name_plural': 'SistemaOperativos',
            },
        ),
        migrations.CreateModel(
            name='SoftwareAntivirus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Software Antivirus')),
            ],
            options={
                'verbose_name': 'Software Antivirus',
                'verbose_name_plural': 'Software Antivirus',
            },
        ),
        migrations.CreateModel(
            name='SoftwareOfimatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Software Ofimática')),
            ],
            options={
                'verbose_name': 'Software Ofimatica',
                'verbose_name_plural': 'Software Ofimatica',
            },
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Tipo Dispositivo')),
            ],
            options={
                'verbose_name': 'Tipo Dispositivo',
                'verbose_name_plural': 'Tipo Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Tipo Equipo')),
            ],
            options={
                'verbose_name': 'Tipo Equipo',
                'verbose_name_plural': 'TipoEquipos',
            },
        ),
        migrations.CreateModel(
            name='TipoImpresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, unique=True, verbose_name='Tipo Impresora')),
            ],
            options={
                'verbose_name': 'Tipo Impresora',
                'verbose_name_plural': 'TipoImpresoras',
            },
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='antivirus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.softwareantivirus'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='ofimatica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.softwareofimatica'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='sistemaOperativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.sistemaoperativo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tecnologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.impresoratecnologia'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipoDispositivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipodispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipoEquipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoequipo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipoImpresora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipoimpresora'),
        ),
    ]
