# Generated by Django 3.1.7 on 2021-04-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20210401_0909'),
        ('inventario', '0003_merge_20210401_0834'),
    ]

    operations = [
    ]
