# Generated by Django 3.2.1 on 2021-05-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20210509_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipocabecera',
            name='condicion',
            field=models.CharField(blank=True, choices=[('1', 'BUENO'), ('2', 'REGULAR'), ('3', 'DAÑADO')], max_length=1, null=True, verbose_name='Condición'),
        ),
        migrations.AlterField(
            model_name='equipodetalle',
            name='cantidad',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='condicion',
            field=models.CharField(blank=True, choices=[('1', 'BUENO'), ('2', 'REGULAR'), ('3', 'DAÑADO')], max_length=1, null=True, verbose_name='Condición'),
        ),
    ]
