# Generated by Django 3.2.1 on 2021-05-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20210514_0254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impresoratecnologia',
            options={'verbose_name': 'Impresora Tecnologia', 'verbose_name_plural': 'Impresora Tecnologia'},
        ),
        migrations.AlterModelOptions(
            name='sistemaoperativo',
            options={'verbose_name': 'Sistema Operativo', 'verbose_name_plural': 'Sistema Operativos'},
        ),
        migrations.AlterModelOptions(
            name='tipoequipo',
            options={'verbose_name': 'Tipo Equipo', 'verbose_name_plural': 'Tipo Equipos'},
        ),
        migrations.AlterModelOptions(
            name='tipoimpresora',
            options={'verbose_name': 'Tipo Impresora', 'verbose_name_plural': 'Tipo Impresoras'},
        ),
    ]
