# Generated by Django 3.2.1 on 2021-05-12 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_auto_20210512_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Condicion',
        ),
    ]
