# Generated by Django 3.1.7 on 2021-04-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_merge_20210401_0914'),
        ('inventario', '0005_merge_20210401_0953'),
        ('inventario', '0003_merge_20210331_2000'),
    ]

    operations = [
    ]
