# Generated by Django 3.2.3 on 2021-05-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20210514_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioTics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80, verbose_name='Item')),
                ('serie', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Serie')),
                ('codigoMies', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Mies')),
                ('condicion', models.CharField(blank=True, choices=[('1', 'NUEVO'), ('2', 'REGULAR'), ('3', 'DAÑADO')], max_length=1, null=True, verbose_name='Condición')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='InventarioTics/%Y/%m/%d/', verbose_name='Foto')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.modelo')),
            ],
            options={
                'verbose_name': 'Inventario Tics',
                'verbose_name_plural': 'Inventario Tics',
            },
        ),
    ]
