# Generated by Django 3.2.3 on 2021-05-18 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_inventariotics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariotics',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='inventariotics',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventario.tipodispositivo'),
        ),
    ]
