# Generated by Django 3.1.7 on 2021-04-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_merge_20210405_0838'),
        ('inventario', '0007_merge_20210405_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariotics',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area'),
        ),
    ]
