# Generated by Django 3.1.7 on 2021-04-03 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_merge_20210401_1134'),
        ('inventario', '0007_merge_20210402_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodistritodetalle',
            name='cabeceraDistrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventario.invetariodistritocabecera'),
        ),
        migrations.AlterField(
            model_name='inventariotics',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area'),
        ),
    ]
