# Generated by Django 3.1.7 on 2021-04-03 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_auto_20210402_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodistritodetalle',
            name='cabeceraDistrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.invetariodistritocabecera'),
        ),
    ]
