# Generated by Django 3.1.7 on 2021-04-03 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20210402_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventariodistritodetalle',
            name='cabeceraDistrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalleCabecera', to='inventario.invetariodistritocabecera'),
        ),
    ]
