# Generated by Django 3.1.7 on 2021-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0011_auto_20210403_2042'),
        ('inventario', '0008_auto_20210405_0842'),
    ]

    operations = [
    ]
