# Generated by Django 3.2.1 on 2021-05-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_cargo_descripcion'),
        ('custodio', '0002_alter_custodio_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodio',
            name='custodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Custodio a asignar:'),
        ),
    ]
