# Generated by Django 3.2 on 2021-05-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
        ('custodio', '0002_alter_custodio_custodioanterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodio',
            name='custodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Empleado Custodio'),
        ),
        migrations.AlterField(
            model_name='custodio',
            name='custodioAnterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custodioAnterior', to='empleado.empleado', verbose_name='Custodio Anterior'),
        ),
    ]
