# Generated by Django 3.2 on 2021-05-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcabecera',
            name='prioridad',
            field=models.CharField(choices=[('1', 'PRESENCIAL'), ('2', 'VIDEO CONFERENCIA'), ('3', 'SKYPE'), ('4', 'TELEFÓNICA')], default='1', max_length=1, verbose_name='Tipo Capacitación'),
        ),
    ]
