# Generated by Django 3.1.7 on 2021-03-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividaddetalle',
            options={'verbose_name': 'Actividad Detalle', 'verbose_name_plural': 'Actividad Detalles'},
        ),
    ]
