# Generated by Django 3.1.7 on 2021-03-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_auto_20210329_1306'),
        ('actividad', '0002_auto_20210329_2051'),
    ]

    operations = [
    ]
