# Generated by Django 3.2.1 on 2021-05-06 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_alter_actividadcabecera_prioridad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prioridad',
        ),
        migrations.AlterField(
            model_name='actividadcabecera',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='actividadcabecera',
            name='prioridad',
            field=models.CharField(choices=[('1', 'ALTA'), ('2', 'MEDIA'), ('3', 'BAJA')], default='1', max_length=1, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='actividaddetalle',
            name='cabeceraActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.actividadcabecera'),
        ),
    ]
