# Generated by Django 3.1.7 on 2021-04-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_merge_20210331_0844'),
        ('actividad', '0003_merge_20210331_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcabecera',
            name='prioridad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividad.prioridad'),
        ),
        migrations.AlterField(
            model_name='actividadcabecera',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsable_de_activiadad', to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='actividadcabecera',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area'),
        ),
        migrations.AlterField(
            model_name='actividadcabecera',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='actividaddetalle',
            name='asunto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividad.asunto'),
        ),
        migrations.AlterField(
            model_name='actividaddetalle',
            name='cabeceraActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actividad.actividadcabecera'),
        ),
    ]
