# Generated by Django 3.2.1 on 2021-05-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_cargo_descripcion'),
        ('actividad', '0003_auto_20210506_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadcabecera',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.area', verbose_name='Ubicación'),
        ),
    ]
