# Generated by Django 3.2 on 2021-05-01 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoRed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('usuario', models.CharField(max_length=50, verbose_name='Usuario')),
                ('direccion_mac', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Mac')),
                ('direccion_ip', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Dirección Ip')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'Acceso Red',
                'verbose_name_plural': 'Acceso Redes',
            },
        ),
    ]
