# Generated by Django 3.1.7 on 2021-03-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
