# Generated by Django 3.1.7 on 2021-03-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0002_auto_20210324_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='estado'),
        ),
    ]
