# Generated by Django 3.1.7 on 2021-03-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0006_auto_20210327_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
