# Generated by Django 3.1.7 on 2021-03-29 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0007_auto_20210328_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 23, 8, 10, 405861), verbose_name='Fecha'),
        ),
    ]
