# Generated by Django 3.1.7 on 2021-03-29 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0008_auto_20210328_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 8, 32, 31, 634539), verbose_name='Fecha'),
        ),
    ]
