# Generated by Django 3.1.7 on 2021-03-29 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0009_auto_20210329_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 13, 6, 47, 9730), verbose_name='Fecha'),
        ),
    ]
