# Generated by Django 3.1.7 on 2021-03-30 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0010_auto_20210329_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 20, 51, 50, 667527), verbose_name='Fecha'),
        ),
    ]
