# Generated by Django 3.1.7 on 2021-03-30 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0010_auto_20210329_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 8, 30, 30, 65426), verbose_name='Fecha'),
        ),
    ]
