# Generated by Django 3.1.7 on 2021-03-30 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0011_auto_20210330_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 11, 57, 2, 104221), verbose_name='Fecha'),
        ),
    ]
