# Generated by Django 3.1.7 on 2021-03-31 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0012_auto_20210330_0042'),
        ('red', '0012_auto_20210330_1157'),
    ]

    operations = [
    ]
