# Generated by Django 3.1.7 on 2021-03-31 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0013_merge_20210331_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 10, 35, 28, 648744), verbose_name='Fecha'),
        ),
    ]
