# Generated by Django 3.1.7 on 2021-03-31 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0014_auto_20210331_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 16, 1, 32, 45153), verbose_name='Fecha'),
        ),
    ]
