# Generated by Django 3.1.7 on 2021-03-31 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0014_auto_20210331_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2021, 3, 31, 11, 37, 30, 458647), verbose_name='Fecha'),
        ),
    ]
