# Generated by Django 3.1.7 on 2021-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0015_auto_20210331_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesored',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
