# Generated by Django 3.1.7 on 2021-04-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0014_auto_20210331_1035'),
        ('red', '0016_auto_20210331_1137'),
    ]

    operations = [
    ]
