# Generated by Django 3.1.7 on 2021-04-01 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0019_merge_20210401_0914'),
        ('red', '0020_auto_20210401_0953'),
        ('red', '0017_merge_20210331_2000'),
    ]

    operations = [
    ]
