# Generated by Django 3.1.7 on 2021-04-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0021_merge_20210401_1307'),
        ('red', '0021_merge_20210401_1134'),
    ]

    operations = [
    ]
