# Generated by Django 3.1.7 on 2021-04-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0021_merge_20210401_1134'),
        ('red', '0021_merge_20210403_0950'),
        ('red', '0021_merge_20210401_1307'),
    ]

    operations = [
    ]
