# Generated by Django 3.1.7 on 2021-04-05 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0022_merge_20210405_0838'),
        ('red', '0022_merge_20210402_0015'),
    ]

    operations = [
    ]
