# Generated by Django 3.2.3 on 2021-05-18 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_estado'),
        ('custodia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custodia',
            name='custodio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado', verbose_name='Custodio'),
        ),
    ]
