# Generated by Django 3.2 on 2021-04-16 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0006_merge_20210405_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitacionCabecera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_inicio', models.TimeField(verbose_name='Hora Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora Fin')),
                ('lugar', models.CharField(max_length=50, verbose_name='Lugar')),
                ('tema', models.CharField(max_length=50, verbose_name='Tema')),
                ('areaSolicitante', models.CharField(max_length=50, verbose_name='Area Solicitante')),
                ('dirigido', models.CharField(max_length=50, verbose_name='Dirigido a')),
                ('objetivo', models.TextField(verbose_name='Objetivo')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Capacitación',
                'verbose_name_plural': 'Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='TipoCapacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Tipo Capacitación')),
            ],
            options={
                'verbose_name': 'Tipo Capacitacion',
                'verbose_name_plural': 'Tipo Capacitaciones',
            },
        ),
        migrations.CreateModel(
            name='CapacitacionDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='observación')),
                ('capacitacionCabecera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.capacitacioncabecera')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Capacitacion Detalle',
                'verbose_name_plural': 'Capacitacion Detalles',
            },
        ),
        migrations.AddField(
            model_name='capacitacioncabecera',
            name='tipoCapacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.tipocapacitacion'),
        ),
    ]
