# Generated by Django 3.1.7 on 2021-04-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_merge_20210331_0844'),
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacioncabecera',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='capacitacioncabecera',
            name='tipoCapacitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.tipocapacitacion'),
        ),
        migrations.AlterField(
            model_name='capacitaciondetalle',
            name='capacitacionCabecera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='capacitacion.capacitacioncabecera'),
        ),
        migrations.AlterField(
            model_name='capacitaciondetalle',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
    ]
