# Generated by Django 3.2 on 2021-05-02 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitacioncabecera',
            options={'verbose_name': 'Capacitacion', 'verbose_name_plural': 'Capacitaciones'},
        ),
    ]
