# Generated by Django 3.2 on 2021-05-01 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_alter_capacitacioncabecera_tipocapacitacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoCapacitacion',
        ),
    ]
