# Generated by Django 3.2.1 on 2021-05-10 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_cargo_descripcion'),
        ('capacitacion', '0002_alter_capacitacioncabecera_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitaciondetalle',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
    ]
