# Generated by Django 3.1.7 on 2021-03-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
            },
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='Universidad')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
            },
        ),
        migrations.CreateModel(
            name='Pasante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Incio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('horas_diarias', models.IntegerField(default=0, verbose_name='Horas Diarias')),
                ('cedula', models.CharField(max_length=10, verbose_name='Cédula')),
                ('telefono', models.CharField(max_length=10, verbose_name='Télefono Movil')),
                ('estado', models.BooleanField(verbose_name='Prácticas profesionales completadas?')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica.carrera')),
                ('tutor_profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Pasante',
                'verbose_name_plural': 'Pasantes',
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica.universidad'),
        ),
    ]
