# Generated by Django 3.2.1 on 2021-05-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasante',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='pasante',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Teléfono Móvil'),
        ),
    ]
