# Generated by Django 3.2 on 2021-04-20 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0006_merge_20210405_0838'),
        ('practica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practica.universidad'),
        ),
        migrations.AlterField(
            model_name='pasante',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practica.carrera'),
        ),
        migrations.AlterField(
            model_name='pasante',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='pasante',
            name='horas_diarias',
            field=models.IntegerField(default=1, verbose_name='Horas Diarias'),
        ),
        migrations.AlterField(
            model_name='pasante',
            name='tutor_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
    ]
