# Generated by Django 3.1.7 on 2021-03-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasante',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
    ]
