# Generated by Django 3.1.7 on 2021-04-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_merge_20210331_0844'),
        ('practica', '0002_auto_20210326_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='universidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practica.universidad'),
        ),
        migrations.AlterField(
            model_name='pasante',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='practica.carrera'),
        ),
        migrations.AlterField(
            model_name='pasante',
            name='tutor_profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleado.empleado'),
        ),
    ]
