# Generated by Django 3.2.1 on 2021-05-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0002_auto_20210506_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='descripcion',
            field=models.CharField(max_length=50, verbose_name='Carrera'),
        ),
    ]
