# Generated by Django 3.2 on 2021-04-18 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practica', '0003_auto_20210401_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasante',
            name='horas_diarias',
            field=models.IntegerField(default=1, verbose_name='Horas Diarias'),
        ),
    ]
